Document: arcv-test-1.2
Title: Debian arcv-test-1.2 Manual
Author: <insert document author here>
Abstract: This manual describes what arcv-test-1.2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/arcv-test-1.2/arcv-test-1.2.sgml.gz

Format: postscript
Files: /usr/share/doc/arcv-test-1.2/arcv-test-1.2.ps.gz

Format: text
Files: /usr/share/doc/arcv-test-1.2/arcv-test-1.2.text.gz

Format: HTML
Index: /usr/share/doc/arcv-test-1.2/html/index.html
Files: /usr/share/doc/arcv-test-1.2/html/*.html
